spring:
  application:
    name: bakery
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}
server:
  port: ${port:8083}
bakery:
  timeToBakePizzaInMillis: 15000
logging:
  level:
    com.epages: INFO
    feign: DEBUG
    org.springframework: INFO
