spring:
  application:
    name: delivery
  rabbitmq:
    host: ${rabbitmq.host:rabbitmq}
    port: ${rabbitmq.port:5672}
server:
  port: ${port:8084}
delivery:
  timeToDeliverInMillis: 15000
  timeToPrepareDeliveryInMillis: 5000

logging:
  level:
    com.epages: INFO
    feign: DEBUG
    org.springframework: INFO
